packages:
  - experiments/*
  - experiments/streams/*
  - packages/*

minimumReleaseAge: 1440

onlyBuiltDependencies:
  - esbuild
  - workerd
  - sharp

catalogs:
  cloudflare:
    "@cloudflare/workers-types": ^4.20260426.1
    wrangler: ^4.85.0
